server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          # github上仓库地址
          uri: https://github.com/BigDragonZ/microservicecloud-config.git